# Generated by Django 4.1 on 2024-06-30 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_token", models.CharField(max_length=10)),
                ("user_id", models.CharField(max_length=255)),
                ("peer_id", models.CharField(max_length=255)),
                ("supplier_id", models.CharField(max_length=255)),
                ("demand_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oauth_state_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="oauth.statesession",
                    ),
                ),
                (
                    "oauth_token_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oauth.tokensession",
                    ),
                ),
            ],
        ),
    ]
